server:
  port: 8080
  servlet:
    context-path: /wechat
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.28.120.80:3306/exhibition_entrance_guard?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  thymeleaf:
    #调试时可用false
    cache: false
    #content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
logging:
  config: classpath:logback.xml
wechat:
  AppID: wx672925c243ea0aaf
  AppSecret: 6943cad5170d4c9bbd8d31751bb2b43b
  token: eking666
#mybatis
mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.eking.tourism.module.*.entity

